name       : python-elementpath
version    : 3.0.2
release    : 5
source     :
    - https://github.com/sissaschool/elementpath/archive/refs/tags/v3.0.2.tar.gz : fe2e600da741c51253fb480e97ab6d8bc86f1619743638877737853d91ba2e36
homepage   : https://github.com/sissaschool/elementpath
license    : MIT
component  : programming.python
summary    : XPath 1.0/2.0 parsers and selectors for ElementTree and lxml
description: |
    The proposal of this package is to provide XPath 1.0 and 2.0 selectors for Python's ElementTree XML data structures, both for the standard ElementTree library and for the lxml.etree library.
build      : |
    %python3_setup
install    : |
    %python3_install
