name       : python-elementpath
version    : 2.5.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/e/elementpath/elementpath-2.4.0.tar.gz : 5b6801b3be94d48d213beb7b8ebad96addb35c95fc6a9c062c80e033b4a32fe8
homepage   : https://github.com/sissaschool/elementpath
license    : MIT
component  : programming.python
summary    : XPath 1.0/2.0 parsers and selectors for ElementTree and lxml
description: |
    The proposal of this package is to provide XPath 1.0 and 2.0 selectors for Python's ElementTree XML data structures, both for the standard ElementTree library and for the lxml.etree library.
build      : |
    %python3_setup
install    : |
    %python3_install
